"""categories

Revision ID: 21914357647b
Revises: 
Create Date: 2026-05-17 17:42:18.008421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21914357647b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('cat_id', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('cat_title', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('cat_href', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('cat_photo', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('id_added', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('id_modify', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('id_deleted', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('date_added', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('date_modify', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('date_deleted', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('ip_address', sa.String(), nullable=True))
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_cat_href'), 'categories', ['cat_href'], unique=False)
    op.create_index(op.f('ix_categories_cat_id'), 'categories', ['cat_id'], unique=False)
    op.create_index(op.f('ix_categories_cat_photo'), 'categories', ['cat_photo'], unique=False)
    op.create_index(op.f('ix_categories_cat_title'), 'categories', ['cat_title'], unique=False)
    op.create_index(op.f('ix_categories_date_added'), 'categories', ['date_added'], unique=False)
    op.create_index(op.f('ix_categories_date_deleted'), 'categories', ['date_deleted'], unique=False)
    op.create_index(op.f('ix_categories_date_modify'), 'categories', ['date_modify'], unique=False)
    op.create_index(op.f('ix_categories_id_added'), 'categories', ['id_added'], unique=False)
    op.create_index(op.f('ix_categories_id_deleted'), 'categories', ['id_deleted'], unique=False)
    op.create_index(op.f('ix_categories_id_modify'), 'categories', ['id_modify'], unique=False)
    op.create_index(op.f('ix_categories_ip_address'), 'categories', ['ip_address'], unique=False)
    op.drop_column('categories', 'id')
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_categories_ip_address'), table_name='categories')
    op.drop_index(op.f('ix_categories_id_modify'), table_name='categories')
    op.drop_index(op.f('ix_categories_id_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_id_added'), table_name='categories')
    op.drop_index(op.f('ix_categories_date_modify'), table_name='categories')
    op.drop_index(op.f('ix_categories_date_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_date_added'), table_name='categories')
    op.drop_index(op.f('ix_categories_cat_title'), table_name='categories')
    op.drop_index(op.f('ix_categories_cat_photo'), table_name='categories')
    op.drop_index(op.f('ix_categories_cat_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_cat_href'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_column('categories', 'ip_address')
    op.drop_column('categories', 'date_deleted')
    op.drop_column('categories', 'date_modify')
    op.drop_column('categories', 'date_added')
    op.drop_column('categories', 'id_deleted')
    op.drop_column('categories', 'id_modify')
    op.drop_column('categories', 'id_added')
    op.drop_column('categories', 'cat_photo')
    op.drop_column('categories', 'cat_href')
    op.drop_column('categories', 'cat_title')
    op.drop_column('categories', 'cat_id')
    # ### end Alembic commands ###
